"""Debt dodate kolone debt_date, number_of_installments

Revision ID: 0ed4636d877c
Revises: f1b0013ead4b
Create Date: 2025-04-20 08:04:04.939251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed4636d877c'
down_revision = 'f1b0013ead4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debt_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('number_of_installments', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.drop_column('number_of_installments')
        batch_op.drop_column('debt_date')

    # ### end Alembic commands ###
