"""User, povratak JMBG kolone

Revision ID: 5bdf6f4a5755
Revises: 0ed4636d877c
Create Date: 2025-04-21 16:43:44.167667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bdf6f4a5755'
down_revision = '0ed4636d877c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('JMBG', sa.String(length=13), nullable=True))
        batch_op.create_unique_constraint(None, ['JMBG'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('JMBG')

    # ### end Alembic commands ###
