"""Izmena tipa kolona sa Float na Numeric u PaySpotTransaction

Revision ID: 615438170d48
Revises: a44857ff2b83
Create Date: 2025-04-28 17:03:19.788495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '615438170d48'
down_revision = 'a44857ff2b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pay_spot_transaction', schema=None) as batch_op:
        batch_op.alter_column('sender_fee',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=True)
        batch_op.alter_column('beneficiary_amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pay_spot_transaction', schema=None) as batch_op:
        batch_op.alter_column('beneficiary_amount',
               existing_type=sa.Numeric(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('sender_fee',
               existing_type=sa.Numeric(),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
