"""User: ponovo obrisana kolona JMBG, kreirana kontrola newsletter

Revision ID: 6bd1cd0ce702
Revises: 5bdf6f4a5755
Create Date: 2025-04-22 16:08:03.420852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6bd1cd0ce702'
down_revision = '5bdf6f4a5755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('newsletter', sa.Boolean(), nullable=False))
        batch_op.drop_index('JMBG')
        batch_op.drop_column('JMBG')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('JMBG', mysql.VARCHAR(length=13), nullable=True))
        batch_op.create_index('JMBG', ['JMBG'], unique=True)
        batch_op.drop_column('newsletter')

    # ### end Alembic commands ###
