"""inicijalna_migracija

Revision ID: 82281611ec29
Revises: 
Create Date: 2025-04-11 06:56:54.666910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82281611ec29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('session_id')

    op.drop_table('sessions')
    op.drop_table('pay_spot_transaction')
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('current_weight',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('wanted_weight',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('animal_categorization', schema=None) as batch_op:
        batch_op.alter_column('fattening_price',
               existing_type=mysql.FLOAT(),
               nullable=True)

    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.alter_column('farm_description',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('product_description',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('product_price_per_unit_farmer',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('JMBG')
        batch_op.drop_column('JMBG')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('JMBG', mysql.VARCHAR(length=13), nullable=True))
        batch_op.create_index('JMBG', ['JMBG'], unique=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('product_price_per_unit_farmer',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('product_description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)

    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.alter_column('farm_description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=False)

    with op.batch_alter_table('animal_categorization', schema=None) as batch_op:
        batch_op.alter_column('fattening_price',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('wanted_weight',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('current_weight',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    op.create_table('pay_spot_transaction',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('invoice_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('merchant_order_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('payspot_group_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('sequence_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('merchant_order_reference', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('payspot_transaction_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('status_trans', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('create_date', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('create_time', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('sender_fee', mysql.FLOAT(), nullable=True),
    sa.Column('farm_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], name='pay_spot_transaction_ibfk_2'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name='pay_spot_transaction_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sessions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('expiry', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('session_id', ['session_id'], unique=True)

    # ### end Alembic commands ###
