"""definisanje Numeric parametara u kolonama (12,2)

Revision ID: b74849fe26a4
Revises: 615438170d48
Create Date: 2025-04-28 17:25:44.652989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b74849fe26a4'
down_revision = '615438170d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pay_spot_transaction', schema=None) as batch_op:
        batch_op.alter_column('sender_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('beneficiary_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pay_spot_transaction', schema=None) as batch_op:
        batch_op.alter_column('beneficiary_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=True)
        batch_op.alter_column('sender_fee',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=True)

    # ### end Alembic commands ###
