"""dodata kolona beneficiary_amount u PaySpotTransaction

Revision ID: f1b0013ead4b
Revises: 82281611ec29
Create Date: 2025-04-11 13:10:44.311967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b0013ead4b'
down_revision = '82281611ec29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pay_spot_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beneficiary_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pay_spot_transaction', schema=None) as batch_op:
        batch_op.drop_column('beneficiary_amount')

    # ### end Alembic commands ###
